import {
  ExerciseCategory,
  LoadUnit,
  MuscleGroup,
  TrackingMode,
} from "../src/generated/prisma/enums";

export interface CatalogExercise {
  name: string;
  muscleGroup: MuscleGroup;
  secondaryMuscles: MuscleGroup[];
  category: ExerciseCategory;
  trackingMode: TrackingMode;
  defaultUnit: LoadUnit;
  description: string;
}

const {
  CHEST,
  BACK,
  SHOULDERS,
  BICEPS,
  TRICEPS,
  FOREARMS,
  QUADS,
  HAMSTRINGS,
  GLUTES,
  CALVES,
  CORE,
  CARDIO,
  FULL_BODY,
} = MuscleGroup;

const { MACHINE, DUMBBELL, BARBELL, BODYWEIGHT, CABLE } = ExerciseCategory;
const { WEIGHT_REPS, REPS_ONLY, TIME, DISTANCE_TIME } = TrackingMode;

/**
 * Catalogue commun (`ownerId = NULL`), partagé par tous les comptes et non
 * modifiable par eux : chacun peut en revanche créer ses propres exercices et
 * ses variantes de machine.
 *
 * Les mouvements au poids du corps sont en `REPS_ONLY` / `BODYWEIGHT` : pour les
 * lester, on crée une variante avec l'unité `KG` (« Lesté »), ce qui garde les
 * deux historiques distincts.
 */
export const EXERCISE_CATALOG: CatalogExercise[] = [
  // ----------------------------------------------------------------- Pectoraux
  {
    name: "Chest Press",
    muscleGroup: CHEST,
    secondaryMuscles: [TRICEPS, SHOULDERS],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé pour les pectoraux sur machine guidée, assis.",
  },
  {
    name: "Développé couché",
    muscleGroup: CHEST,
    secondaryMuscles: [TRICEPS, SHOULDERS],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé à la barre sur banc plat.",
  },
  {
    name: "Développé incliné barre",
    muscleGroup: CHEST,
    secondaryMuscles: [SHOULDERS, TRICEPS],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé à la barre sur banc incliné, haut des pectoraux.",
  },
  {
    name: "Développé couché haltères",
    muscleGroup: CHEST,
    secondaryMuscles: [TRICEPS, SHOULDERS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé aux haltères sur banc plat. Charge par haltère.",
  },
  {
    name: "Développé incliné haltères",
    muscleGroup: CHEST,
    secondaryMuscles: [SHOULDERS, TRICEPS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé aux haltères sur banc incliné. Charge par haltère.",
  },
  {
    name: "Pec Deck",
    muscleGroup: CHEST,
    secondaryMuscles: [SHOULDERS],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Écarté sur machine, bras semi-tendus.",
  },
  {
    name: "Écarté à la poulie",
    muscleGroup: CHEST,
    secondaryMuscles: [SHOULDERS],
    category: CABLE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Écarté aux câbles, tension continue sur les pectoraux.",
  },
  {
    name: "Pompes",
    muscleGroup: CHEST,
    secondaryMuscles: [TRICEPS, CORE],
    category: BODYWEIGHT,
    trackingMode: REPS_ONLY,
    defaultUnit: LoadUnit.BODYWEIGHT,
    description: "Poids du corps. Créer une variante « Lestée » pour ajouter une charge.",
  },
  {
    name: "Dips",
    muscleGroup: CHEST,
    secondaryMuscles: [TRICEPS, SHOULDERS],
    category: BODYWEIGHT,
    trackingMode: REPS_ONLY,
    defaultUnit: LoadUnit.BODYWEIGHT,
    description: "Aux barres parallèles. Créer une variante « Lestée » pour ajouter une charge.",
  },

  // ----------------------------------------------------------------------- Dos
  {
    name: "Lat Pulldown",
    muscleGroup: BACK,
    secondaryMuscles: [BICEPS, FOREARMS],
    category: CABLE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Tirage vertical à la poulie haute, prise large.",
  },
  {
    name: "Seated Row",
    muscleGroup: BACK,
    secondaryMuscles: [BICEPS, FOREARMS],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Tirage horizontal assis, dos des épaules et milieu du dos.",
  },
  {
    name: "Rowing barre",
    muscleGroup: BACK,
    secondaryMuscles: [BICEPS, CORE],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Tirage à la barre, buste penché.",
  },
  {
    name: "Rowing haltère",
    muscleGroup: BACK,
    secondaryMuscles: [BICEPS, CORE],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Tirage unilatéral à l'haltère, appui sur un banc.",
  },
  {
    name: "Tractions",
    muscleGroup: BACK,
    secondaryMuscles: [BICEPS, FOREARMS],
    category: BODYWEIGHT,
    trackingMode: REPS_ONLY,
    defaultUnit: LoadUnit.BODYWEIGHT,
    description: "À la barre fixe. Créer une variante « Lestée » pour ajouter une charge.",
  },
  {
    name: "Soulevé de terre",
    muscleGroup: BACK,
    secondaryMuscles: [HAMSTRINGS, GLUTES, FOREARMS],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Tirage de la barre depuis le sol, chaîne postérieure complète.",
  },
  {
    name: "Face Pull",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [BACK],
    category: CABLE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Tirage à la corde vers le visage, arrière des épaules.",
  },
  {
    name: "Pull-over à la poulie",
    muscleGroup: BACK,
    secondaryMuscles: [CHEST, TRICEPS],
    category: CABLE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Bras tendus, amplitude sur les grands dorsaux.",
  },
  {
    name: "Shrug",
    muscleGroup: BACK,
    secondaryMuscles: [FOREARMS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Haussement d'épaules, trapèzes supérieurs.",
  },

  // ------------------------------------------------------------------- Épaules
  {
    name: "Shoulder Press",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [TRICEPS],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé épaules sur machine guidée.",
  },
  {
    name: "Développé militaire",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [TRICEPS, CORE],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé à la barre debout, au-dessus de la tête.",
  },
  {
    name: "Développé épaules haltères",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [TRICEPS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Développé assis aux haltères. Charge par haltère.",
  },
  {
    name: "Lateral Raise",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Élévations latérales, faisceau moyen. Charge par haltère.",
  },
  {
    name: "Élévations frontales",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Élévations devant soi, faisceau antérieur.",
  },
  {
    name: "Oiseau",
    muscleGroup: SHOULDERS,
    secondaryMuscles: [BACK],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Buste penché, arrière des épaules.",
  },

  // -------------------------------------------------------------------- Biceps
  {
    name: "Biceps Curl",
    muscleGroup: BICEPS,
    secondaryMuscles: [FOREARMS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Curl aux haltères. Charge par haltère.",
  },
  {
    name: "Curl barre",
    muscleGroup: BICEPS,
    secondaryMuscles: [FOREARMS],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Curl à la barre droite ou EZ.",
  },
  {
    name: "Curl marteau",
    muscleGroup: BICEPS,
    secondaryMuscles: [FOREARMS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Curl en prise neutre, brachial et avant-bras.",
  },
  {
    name: "Curl pupitre",
    muscleGroup: BICEPS,
    secondaryMuscles: [],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Curl sur pupitre, bras bloqués.",
  },

  // ------------------------------------------------------------------- Triceps
  {
    name: "Triceps Pushdown",
    muscleGroup: TRICEPS,
    secondaryMuscles: [],
    category: CABLE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Extension à la poulie haute, barre ou corde.",
  },
  {
    name: "Extension nuque",
    muscleGroup: TRICEPS,
    secondaryMuscles: [],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Extension au-dessus de la tête, longue portion du triceps.",
  },
  {
    name: "Barre au front",
    muscleGroup: TRICEPS,
    secondaryMuscles: [],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Extension allongé, barre EZ vers le front.",
  },

  // -------------------------------------------------------------------- Jambes
  {
    name: "Leg Press",
    muscleGroup: QUADS,
    secondaryMuscles: [GLUTES, HAMSTRINGS],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Presse à cuisses inclinée ou horizontale.",
  },
  {
    name: "Leg Extension",
    muscleGroup: QUADS,
    secondaryMuscles: [],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Extension des genoux assis, quadriceps isolés.",
  },
  {
    name: "Leg Curl",
    muscleGroup: HAMSTRINGS,
    secondaryMuscles: [CALVES],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Flexion des genoux, ischio-jambiers.",
  },
  {
    name: "Squat",
    muscleGroup: QUADS,
    secondaryMuscles: [GLUTES, CORE, HAMSTRINGS],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Flexion complète barre sur les épaules.",
  },
  {
    name: "Hack Squat",
    muscleGroup: QUADS,
    secondaryMuscles: [GLUTES],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Squat guidé sur machine inclinée.",
  },
  {
    name: "Fentes haltères",
    muscleGroup: QUADS,
    secondaryMuscles: [GLUTES, HAMSTRINGS],
    category: DUMBBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Fentes avant ou marchées, un haltère dans chaque main.",
  },
  {
    name: "Soulevé de terre roumain",
    muscleGroup: HAMSTRINGS,
    secondaryMuscles: [GLUTES, BACK],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Jambes semi-tendues, étirement des ischio-jambiers.",
  },
  {
    name: "Hip Thrust",
    muscleGroup: GLUTES,
    secondaryMuscles: [HAMSTRINGS],
    category: BARBELL,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Extension de hanche dos appuyé sur un banc.",
  },
  {
    name: "Calf Raise",
    muscleGroup: CALVES,
    secondaryMuscles: [],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Extension des chevilles, mollets.",
  },
  {
    name: "Abducteurs machine",
    muscleGroup: GLUTES,
    secondaryMuscles: [],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Écartement des cuisses assis, moyen fessier.",
  },
  {
    name: "Adducteurs machine",
    muscleGroup: QUADS,
    secondaryMuscles: [],
    category: MACHINE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Rapprochement des cuisses assis, adducteurs.",
  },

  // -------------------------------------------------------------------- Gainage
  {
    name: "Gainage",
    muscleGroup: CORE,
    secondaryMuscles: [SHOULDERS],
    category: BODYWEIGHT,
    trackingMode: TIME,
    defaultUnit: LoadUnit.BODYWEIGHT,
    description: "Planche sur les avant-bras, mesurée en durée.",
  },
  {
    name: "Crunch à la poulie",
    muscleGroup: CORE,
    secondaryMuscles: [],
    category: CABLE,
    trackingMode: WEIGHT_REPS,
    defaultUnit: LoadUnit.KG,
    description: "Flexion du buste à genoux, corde à la poulie haute.",
  },
  {
    name: "Relevé de jambes suspendu",
    muscleGroup: CORE,
    secondaryMuscles: [FOREARMS],
    category: BODYWEIGHT,
    trackingMode: REPS_ONLY,
    defaultUnit: LoadUnit.BODYWEIGHT,
    description: "Suspendu à la barre, remontée des jambes.",
  },

  // --------------------------------------------------------------------- Cardio
  {
    name: "Tapis de course",
    muscleGroup: CARDIO,
    secondaryMuscles: [FULL_BODY],
    category: ExerciseCategory.CARDIO,
    trackingMode: DISTANCE_TIME,
    defaultUnit: LoadUnit.NONE,
    description: "Course ou marche, suivi en distance et durée.",
  },
  {
    name: "Rameur",
    muscleGroup: CARDIO,
    secondaryMuscles: [BACK, FULL_BODY],
    category: ExerciseCategory.CARDIO,
    trackingMode: DISTANCE_TIME,
    defaultUnit: LoadUnit.NONE,
    description: "Ergomètre à ramer, suivi en distance et durée.",
  },
  {
    name: "Vélo elliptique",
    muscleGroup: CARDIO,
    secondaryMuscles: [FULL_BODY],
    category: ExerciseCategory.CARDIO,
    trackingMode: DISTANCE_TIME,
    defaultUnit: LoadUnit.NONE,
    description: "Elliptique, suivi en distance et durée.",
  },
  {
    name: "Vélo",
    muscleGroup: CARDIO,
    secondaryMuscles: [QUADS],
    category: ExerciseCategory.CARDIO,
    trackingMode: DISTANCE_TIME,
    defaultUnit: LoadUnit.NONE,
    description: "Vélo d'appartement, suivi en distance et durée.",
  },
];
